/*

  insert-portfolio-fund.sql
  Sam Matthews
  27th October 2018

*/

TRUNCATE TABLE portfolio_fund;

INSERT INTO portfolio_fund VALUES ('TRUST','MPC','MILFORD');
INSERT INTO portfolio_fund VALUES ('TRUST','MPD','MILFORD');
INSERT INTO portfolio_fund VALUES ('TRUST','MPB','MILFORD');
INSERT INTO portfolio_fund VALUES ('TRUST','MPG','MILFORD');
INSERT INTO portfolio_fund VALUES ('TRUST','MPT','MILFORD');
INSERT INTO portfolio_fund VALUES ('TRUST','MPY','MILFORD');

INSERT INTO portfolio_fund VALUES ('JOINT','MPC','MILFORD');
INSERT INTO portfolio_fund VALUES ('JOINT','MPD','MILFORD');
INSERT INTO portfolio_fund VALUES ('JOINT','MPB','MILFORD');
INSERT INTO portfolio_fund VALUES ('JOINT','MPG','MILFORD');
INSERT INTO portfolio_fund VALUES ('JOINT','MPT','MILFORD');
INSERT INTO portfolio_fund VALUES ('JOINT','MPY','MILFORD');

INSERT INTO portfolio_fund VALUES ('KATE','MPC','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPD','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPB','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPG','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPT','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPY','MILFORD');
INSERT INTO portfolio_fund VALUES ('KATE','MPA','MILFORD');

INSERT INTO portfolio_fund VALUES ('KIWI-SAM','APA','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','EMF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','EUF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','FNZ','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','OZY','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','TNZ','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','TWF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','USF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','USG','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','USV','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','MDZ','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','MZY','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','USM','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','USS','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','ASD','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','DIV','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','ASF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','ASP','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','ASR','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('KIWI-SAM','NPF','SMARTSHARES');

INSERT INTO portfolio_fund VALUES ('SAM','APA','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','EMF','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','EUF','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','FNZ','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','OZY','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','TNZ','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','TWF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','USF','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','USG','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','USV','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','MDZ','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','MZY','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','USM','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','USS','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','ASD','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','DIV','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','ASF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','ASP','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','ASR','SHARESIES');
INSERT INTO portfolio_fund VALUES ('SAM','NPF','SMARTSHARES');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_CI','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_HI','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_EM','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_I','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_E','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_G','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_R','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','AIF_RE','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','FPI','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','FPP','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','FPZ','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','FPA','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','FPG','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','NPC','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','NPE','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','NPG','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','NPU','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','NPH','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','VHF','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','VIF','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','APZ','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','APE','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','APS','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','APG','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPP','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPA','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPY','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPT','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPG','INVESTNOW');
INSERT INTO portfolio_fund VALUES ('SAM','DPD','INVESTNOW');


